// Interaction state belongs here. Renderers consume it; library entries never choose a camera.
import {BUILDINGS,PROPS,ELEVATION,AddCommand,AddManyCommand,MaterialCommand,clone} from './builder-model.js?v=2.22.0';
export function createBuilderFlow(e){
 const w=e.walk,s=w.state,state={tool:'select',item:s.item,roadStart:null};
 Object.defineProperty(s,'mode',{get:()=>state.tool==='environment'?'paint':state.tool,set:v=>{state.tool=v==='paint'?'environment':v;},configurable:true});
 Object.defineProperty(s,'item',{get:()=>state.item,set:v=>{state.item=v;},configurable:true});
 Object.defineProperty(e,'placement',{get:()=>state.tool==='place'?{...state.item,rot:s.rot||0}:null,set:v=>{if(v){state.item=v;state.tool='place';}else if(state.tool==='place')state.tool='select';},configurable:true});
 Object.defineProperty(e,'editorMode',{get:()=>['terrain','environment','analysis'].includes(state.tool)?state.tool:'select',set:v=>{state.tool=v;},configurable:true});
 function ready(){if(s.copy){e.toast('Apply or Cancel the current edit first');return false;}e.cancelInteraction();return true;}
 function select(){if(!ready())return false;w.closePanels();state.tool='select';state.roadStart=null;e.curveDraft=null;s.tool='select';s.ghost=null;s.key='';e.draw();return true;}
 function normalize(item){const defaults=item.type==='building'?BUILDINGS[item.archetype]:item.type==='prop'?PROPS[item.kind]:item.type==='elevation'?ELEVATION[item.kind]:item.type==='natural'?{r:item.kind==='tree'?.8:item.kind==='bush'?1.7:2,h:item.kind==='tree'?7.8:item.kind==='bush'?1.5:2.4}:{};return {...defaults,...item,key:item.key||item.assetId||item.archetype||item.kind||item.type,label:item.label||'Object'};}
 function choose(item){if(!ready())return false;if(!s.building&&!s.overview)w.action('build');w.closePanels();state.item=normalize(item);state.tool='place';state.roadStart=null;e.curveDraft=null;e.selected.clear();s.selectedId=null;s.tool='place';s.rot=0;s.fixedPosition=null;s.ghost=null;s.key='';e.toast('Place · '+state.item.label);e.draw();return true;}
 function terrain(paint=false){if(!ready())return false;if(e.layerLocked('terrain')){e.toast('Unlock Terrain in Layers first');return false;}if(!s.building&&!s.overview)w.action('build');w.closePanels();state.tool=paint?'environment':'terrain';state.roadStart=null;e.curveDraft=null;e.selected.clear();s.selectedId=null;s.tool='terrain';s.brush=e.brush.tool;s.brushRadius=e.brush.radius;s.key='';e.draw();return true;}
 function cancel(){if(s.copy){w.cancelEdit();return;}if(state.roadStart||e.curveDraft){state.roadStart=null;e.curveDraft=null;s.key='';e.draw();return;}select();}
 function switchView(){if(!ready())return false;if(!s.building&&!s.overview)w.action('build');w.switchView();e.draw();return true;}
 function special(){return state.tool==='place'&&!s.copy&&!['building','prop','elevation','natural'].includes(state.item?.type);}
 function pointPlan(point){if(!point)return null;const p={...state.item,rot:s.rot||0},q=e.snapRoadPoint(point);if(p.type==='road'){return {objects:state.roadStart?[e.roadFromPoints(state.roadStart,q,p.kind)]:[],label:state.roadStart?'Set end':'Set start',point:q};}if(p.type==='roadcurve'){const d=e.curveDraft;return {objects:d?.control?e.curveSegments(d.start,d.control,q,p.kind):[],label:!d?'Set start':!d.control?'Set bend':'Set end',point:q};}return {objects:e.makePlacement(p,point.x,point.z),label:'Place '+p.label,point};}
 function commitPoint(point){const plan=pointPlan(point);if(!plan)return;if(state.item.type==='road'&&!state.roadStart){state.roadStart=plan.point;s.key='';e.toast('Place road · choose end');return;}if(state.item.type==='roadcurve'&&!e.curveDraft?.control){if(!e.curveDraft)e.curveDraft={start:plan.point,control:null};else e.curveDraft.control=plan.point;s.key='';return;}if(plan.objects.length){e.commands.execute(new AddManyCommand(e.doc,plan.objects));state.roadStart=null;e.curveDraft=null;s.key='';e.toast('Placed · '+state.item.label);}}
 function paint(point){const changes=new Map();e.materialApply(point.x,point.z,changes);if(changes.size)e.commands.commitApplied(new MaterialCommand(e,[...changes.values()]));}
 function label(){if(!s.building&&!s.overview)return 'TEST';if(s.copy)return (s.moveId?'MOVE':'COPY')+' · Apply or Cancel';if(state.tool==='place')return 'PLACE · '+state.item.label;if(state.tool==='terrain')return 'TERRAIN · '+({level:'Flatten'}[e.brush.tool]||e.brush.tool);if(state.tool==='environment')return 'PAINT · '+e.materialBrush.material;if(state.tool==='analysis')return 'ANALYSIS';if(s.tool==='rotate-tool')return 'ROTATE · Selected object';if(s.tool==='scale-tool')return 'RESIZE · Selected object';return s.selectedId||e.selected.size?'SELECT · Object selected':'SELECT';}
 return {state,select,choose,terrain,cancel,switchView,special,pointPlan,commitPoint,paint,label,ready};
}
