/* Match menus own only canvas presentation and navigation. Gameplay state, timers,
 * network messages and relationship colors are supplied by the client. */
import { THEME, drawPanel, drawButton, drawLabel } from './native-ui.js?v=2.7.0';

const finite=(value,fallback=0)=>Number.isFinite(Number(value))?Number(value):fallback;
const clamp=(value,min,max)=>Math.max(min,Math.min(max,finite(value)));
const color=(key,fallback)=>typeof THEME?.[key]==='string'?THEME[key]:fallback;
export const MATCH_MENU_METRICS=Object.freeze({space:8,padding:16,row:48,control:44,bodyType:14,labelType:16});
const C={background:color('bg','#090d10'),panel:color('panel','#11181d'),raised:color('panelRaised','#1b252c'),line:color('border','#344149'),text:color('text','#f3f6f5'),muted:color('muted','#a6b3bc'),accent:color('accent','#d7ff58')};
export function matchMenuContains(r,x,y){return !!r&&x>=r.x&&y>=r.y&&x<=r.x+r.w&&y<=r.y+r.h;}
const intersect=(a,b)=>{const x=Math.max(a.x,b.x),y=Math.max(a.y,b.y),right=Math.min(a.x+a.w,b.x+b.w),bottom=Math.min(a.y+a.h,b.y+b.h);return right>x&&bottom>y?{x,y,w:right-x,h:bottom-y}:null;};
export function matchMenuViewport({w=960,h=640,safe={}}={}){w=Math.max(1,finite(w,960));h=Math.max(1,finite(h,640));const left=clamp(safe.left,0,w),top=clamp(safe.top,0,h),right=clamp(safe.right,0,w-left),bottom=clamp(safe.bottom,0,h-top),margin=Math.min(16,Math.max(4,Math.min(w-left-right,h-top-bottom)/24));return{x:left+margin,y:top+margin,w:Math.max(1,w-left-right-margin*2),h:Math.max(1,h-top-bottom-margin*2),screen:{x:0,y:0,w,h}};}
function centered(view,w,h){w=Math.min(view.w,w);h=Math.min(view.h,h);return{x:view.x+(view.w-w)/2,y:view.y+(view.h-h)/2,w,h};}
function rr(c,r,fill,stroke,radius=THEME.radius){drawPanel(c,r,{fill,stroke,radius:Math.min(radius,THEME.radius)});}
function clipText(c,text,width){text=String(text??'');if(width<=0)return'';if(c.measureText(text).width<=width)return text;let low=0,high=text.length;while(low<high){const mid=Math.ceil((low+high)/2);if(c.measureText(text.slice(0,mid)+'…').width<=width)low=mid;else high=mid-1;}return low?text.slice(0,low)+'…':'';}
function label(c,text,x,y,{size=14,weight=600,fill=C.text,align='left',width=Infinity}={}){c.save();c.font=`${weight} ${size}px ${THEME.font}`;const available=Number.isFinite(width)?Math.max(0,width):Math.max(1,c.measureText(String(text??'')).width+1),value=clipText(c,text,available),left=align==='center'?x-available/2:align==='right'?x-available:x;drawLabel(c,value,{x:left,y:y-size,w:available,h:size*2},{color:fill,fontSize:size,weight,align});c.restore();}
function button(c,r,text,{active=false,primary=false,disabled=false}={}){drawButton(c,r,{text,focused:active,primary:primary&&!disabled,disabled,fontSize:14});}
function backdrop(c,view,opacity=.78){c.fillStyle=`rgba(3,6,8,${opacity})`;c.fillRect(0,0,view.screen.w,view.screen.h);}
function scrollbar(c,layout){if(!layout.maxScroll||!layout.body)return;const b=layout.body,track={x:b.x+b.w-3,y:b.y,w:3,h:b.h},thumbH=Math.max(24,b.h*b.h/layout.contentH),thumb={x:track.x,y:b.y+(b.h-thumbH)*layout.scroll/layout.maxScroll,w:3,h:thumbH};rr(c,track,C.line,null,2);rr(c,thumb,C.accent,null,2);}
function decorateScroll(layout){const {body}=layout;layout.maxScroll=Math.max(0,layout.contentH-body.h);layout.scroll=clamp(layout.scroll,0,layout.maxScroll);return layout;}
function hit(id,r,action,extra={}){return{id,...r,action,...extra};}

/** All participants are retained in rows/focusTargets; only paint/hit geometry is clipped. */
export function layoutMatchScoreboard(options={}){
  const view=matchMenuViewport(options),rows=Array.isArray(options.rows)?options.rows:[],results=options.kind==='results',panel=centered(view,800,Math.min(648,Math.max(272,164+rows.length*48))),pad=16,headerH=124,footerH=60;
  const body={x:panel.x+pad,y:panel.y+headerH,w:Math.max(1,panel.w-pad*2),h:Math.max(1,panel.h-headerH-footerH)},layout=decorateScroll({kind:results?'results':'scoreboard',view,panel,body,rows:[],rowH:48,contentH:rows.length*48,scroll:options.scroll||0});
  const close=results?null:{x:panel.x+panel.w-104,y:panel.y+12,w:88,h:44},previous={x:panel.x+panel.w-112,y:panel.y+panel.h-52,w:44,h:44},next={x:panel.x+panel.w-60,y:previous.y,w:44,h:44};
  const columns={name:body.x+12,kills:body.x+body.w-120,deaths:body.x+body.w-72,ratio:body.x+body.w-8};
  // On compact widths, names keep at least 84 px while statistics remain legible.
  if(body.w<360){columns.kills=body.x+body.w-102;columns.deaths=body.x+body.w-63;columns.ratio=body.x+body.w-8;}
  layout.close=close;layout.previous=previous;layout.next=next;layout.columns=columns;layout.hits=[];layout.focusTargets=[];
  rows.forEach((player,index)=>{const r={x:body.x,y:body.y+index*48-layout.scroll,w:body.w-8,h:48},visible=intersect(r,body),item=hit(`player:${String(player.id??index)}`,r,'inspect',{player,index,contentY:index*48,scrollItem:true});layout.rows.push({...item,visible});layout.focusTargets.push(item);if(visible&&visible.h>=44)layout.hits.push({...item,...visible});});
  if(close){const target=hit('close',close,'back');layout.hits.push(target);layout.focusTargets.push(target);}
  for(const [id,r,direction,disabled] of [['previous',previous,-1,layout.scroll<=0],['next',next,1,layout.scroll>=layout.maxScroll]]){const target=hit(id,r,'page',{direction,disabled});layout.hits.push(target);layout.focusTargets.push(target);}
  layout.visibleRange={first:rows.length?Math.floor(layout.scroll/48)+1:0,last:Math.min(rows.length,Math.ceil((layout.scroll+body.h)/48)),total:rows.length};return layout;
}
export function drawMatchScoreboard(c,options={}){
  const l=layoutMatchScoreboard(options),{panel:p,body:b,columns:col}=l,focusId=options.focusId||'';c.save();backdrop(c,l.view);rr(c,p,C.panel,C.line);
  label(c,options.title||(l.kind==='results'?'FINAL STANDINGS':'SCOREBOARD'),p.x+16,p.y+30,{size:20,weight:800,fill:options.accent||C.accent,width:p.w-(l.close?136:32)});
  const subtitle=String(options.subtitle||`${l.rows.length} PLAYERS`),segments=subtitle.split(' · '),twoLines=subtitle.startsWith('FINAL STANDINGS · ');label(c,twoLines?segments[0]:subtitle,p.x+16,p.y+60,{fill:C.muted,width:p.w-32});label(c,twoLines?segments.slice(1).join(' · '):`${l.rows.length} PLAYERS`,p.x+16,p.y+82,{fill:C.muted,width:p.w-32});
  label(c,'PLAYER',col.name,p.y+110,{size:14,fill:C.muted});for(const [text,x] of [['K',col.kills],['D',col.deaths],['K/D',col.ratio]])label(c,text,x,p.y+110,{fill:C.muted,align:'right'});
  c.save();c.beginPath();c.rect(b.x,b.y,b.w,b.h);c.clip();
  for(const row of l.rows){if(!row.visible)continue;const player=row.player,self=String(player.id)===String(options.selfId),selected=row.id===focusId;rr(c,{x:row.x,y:row.y+2,w:row.w,h:44},selected?'#273720':self?'#202a22':row.index%2?'#151f25':'#11191e',selected?C.accent:null,6);const stripe=player.color||(self?C.accent:C.muted);c.fillStyle=stripe;c.fillRect(row.x+2,row.y+10,3,28);
    const name=`${player.godMode?'◆ ':''}${String(player.name||'Player')}`,nameW=col.kills-col.name-20;label(c,name,col.name,row.y+17,{size:15,weight:self?700:600,width:nameW});const detail=[self?'YOU':'',player.bot?'BOT':'',player.teamLabel||'',player.godMode?'ADMIN':''].filter(Boolean).join(' · ');label(c,detail||'PLAYER',col.name,row.y+35,{size:14,fill:stripe,width:nameW});
    const kills=Math.max(0,finite(player.kills)),deaths=Math.max(0,finite(player.deaths)),ratio=deaths?(kills/deaths).toFixed(2):kills?String(kills):'0.00';for(const [value,x,fill] of [[kills,col.kills,C.text],[deaths,col.deaths,C.muted],[ratio,col.ratio,C.muted]])label(c,String(value),x,row.y+24,{size:14,align:'right',fill});
  }c.restore();scrollbar(c,l);
  if(!l.rows.length)label(c,'No players yet',b.x+b.w/2,b.y+24,{align:'center',fill:C.muted});
  if(l.close)button(c,l.close,options.controller?'B  BACK':'BACK',{active:focusId==='close'});
  const {first,last,total}=l.visibleRange;label(c,options.footer||`${first}–${last} OF ${total}`,p.x+16,p.y+p.h-30,{fill:C.muted,width:p.w-144});
  for(const id of ['previous','next']){const target=l.hits.find(h=>h.id===id);button(c,target,id==='previous'?'↑':'↓',{disabled:target.disabled,active:focusId===id});}
  c.restore();return l;
}

export function layoutMatchShop(options={}){
  const view=matchMenuViewport(options),items=Array.isArray(options.items)?options.items:[],cols=view.w>=640?3:view.w>=352?2:1,rowH=72,gap=8,headerH=100,footerH=48,panel=centered(view,768,Math.max(248,headerH+Math.ceil(items.length/cols)*(rowH+gap)-gap+footerH)),body={x:panel.x+16,y:panel.y+headerH,w:Math.max(1,panel.w-32),h:Math.max(1,panel.h-headerH-footerH)},layout=decorateScroll({kind:'shop',view,panel,body,cols,rowH,contentH:Math.max(0,Math.ceil(items.length/cols)*(rowH+gap)-gap),scroll:options.scroll||0,items:[],hits:[],focusTargets:[]}),itemW=(body.w-gap*(cols-1))/cols;
  items.forEach((item,index)=>{const row=Math.floor(index/cols),r={x:body.x+(index%cols)*(itemW+gap),y:body.y+row*(rowH+gap)-layout.scroll,w:itemW,h:rowH},target=hit(`shop:${item.id??index}`,r,'buy',{index,item,contentY:row*(rowH+gap),scrollItem:true,disabled:item.disabled===true}),visible=intersect(r,body);layout.items.push({...target,visible});layout.focusTargets.push(target);if(visible&&visible.h>=44)layout.hits.push({...target,...visible});});layout.close={x:panel.x+panel.w-104,y:panel.y+12,w:88,h:44};const close=hit('close',layout.close,'back');layout.hits.push(close);layout.focusTargets.push(close);return layout;
}
export function drawMatchShop(c,options={}){const l=layoutMatchShop(options),p=l.panel;c.save();backdrop(c,l.view,.6);rr(c,p,C.panel,C.line);label(c,'SUPPLY SHOP',p.x+16,p.y+29,{size:20,weight:800,fill:C.accent,width:p.w-128});button(c,l.close,options.controller?'B MENU':'MENU',{active:options.focusId==='close'});label(c,`$${Math.max(0,finite(options.cash))}${options.seconds==null?' AVAILABLE':` · DEPLOY IN ${Math.max(0,Math.ceil(finite(options.seconds)))}s`}`,p.x+16,p.y+60,{size:14,width:p.w-32});label(c,options.subtitle||'Buy supplies for the next round',p.x+16,p.y+83,{size:14,fill:C.muted,width:p.w-32});c.save();c.beginPath();c.rect(l.body.x,l.body.y,l.body.w,l.body.h);c.clip();for(const target of l.items){if(!target.visible)continue;const item=target.item,active=options.focusId?options.focusId===target.id:options.selectedIndex===target.index;rr(c,target,active?'#293820':C.raised,active?C.accent:C.line,8);label(c,`${target.index+1}  ${item.label||item.id}`,target.x+12,target.y+23,{size:15,weight:700,fill:item.disabled?C.muted:C.text,width:target.w-24});const status=item.status||`$${Math.max(0,finite(item.price))}`;label(c,status,target.x+12,target.y+49,{size:14,fill:item.disabled?C.muted:C.accent,width:target.w-24});}c.restore();scrollbar(c,l);label(c,options.controller?'D-PAD SELECT · A BUY':'TAP TO BUY · 1–6 QUICK BUY',p.x+16,p.y+p.h-23,{size:14,fill:C.muted,width:p.w-32});c.restore();return l;}

export function layoutMatchDeath(options={}){const view=matchMenuViewport(options),panel=centered(view,512,options.allowLoadout===false?240:296),loadout=options.allowLoadout===false?null:{x:panel.x+16,y:panel.y+panel.h-60,w:panel.w-32,h:44};return{kind:'death',view,panel,loadout,hits:loadout?[hit('loadout',loadout,'loadout')]:[],focusTargets:loadout?[hit('loadout',loadout,'loadout')]:[]};}
export function drawMatchDeath(c,options={}){const l=layoutMatchDeath(options),p=l.panel,accent=options.accent||'#ff6973';c.save();if(options.backdrop!==false)backdrop(c,l.view,.64);rr(c,p,C.panel,C.line);label(c,'ELIMINATED',p.x+16,p.y+36,{size:28,weight:800,fill:accent,width:p.w-32});label(c,options.attacker||'Preparing your next spawn',p.x+16,p.y+76,{size:16,weight:700,width:p.w-32});label(c,options.detail||'',p.x+16,p.y+105,{size:14,fill:C.muted,width:p.w-32});label(c,options.nextLoadout?`NEXT SPAWN · ${options.nextLoadout}`:'',p.x+16,p.y+137,{size:14,fill:C.accent,width:p.w-32});const bar={x:p.x+16,y:p.y+164,w:p.w-32,h:4};rr(c,bar,C.line,null,2);if(options.progress>0)rr(c,{...bar,w:bar.w*clamp(options.progress,0,1)},accent,null,2);label(c,options.status||'RESPAWNING',p.x+16,p.y+193,{size:16,weight:700,width:p.w-32});if(l.loadout)button(c,l.loadout,options.controller?'A / Y  CHANGE LOADOUT':'CHANGE LOADOUT',{active:options.focusId==='loadout'});c.restore();return l;}

export function layoutMatchTarget(options={}){
  const view=matchMenuViewport(options),wide=view.w>=480&&view.w/view.h>1.45,gap=16,sidebar=wide?Math.min(240,Math.max(192,view.w*.32)):0,headerH=wide?0:76,footerH=wide?0:124,size=Math.max(1,Math.min(wide?view.w-sidebar-gap:view.w,view.h-headerH-footerH,640)),panel=wide?centered(view,size+sidebar+gap,Math.max(size,264)):centered(view,Math.min(view.w,Math.max(320,size+32)),headerH+size+footerH),map=wide?{x:panel.x,y:panel.y+(panel.h-size)/2,w:size,h:size}:{x:panel.x+(panel.w-size)/2,y:panel.y+headerH,w:size,h:size},rail=wide?{x:map.x+map.w+gap,y:panel.y,w:sidebar,h:panel.h}:{x:panel.x,y:map.y+map.h,w:panel.w,h:footerH};
  const confirm=wide?{x:rail.x+16,y:rail.y+rail.h-60,w:rail.w-32,h:44}:{x:rail.x+rail.w/2+4,y:rail.y+rail.h-60,w:rail.w/2-20,h:44},cancel=wide?{x:rail.x+16,y:confirm.y-52,w:rail.w-32,h:44}:{x:rail.x+16,y:confirm.y,w:rail.w/2-20,h:44};return{kind:'target',view,panel,map,rail,wide,confirm,cancel,hits:[hit('target',map,'target'),hit('cancel',cancel,'back'),hit('confirm',confirm,'confirm')],focusTargets:[hit('cancel',cancel,'back'),hit('confirm',confirm,'confirm')]};
}
/** Draw chrome before the client paints the tactical map and gameplay-colored markers. */
export function drawMatchTarget(c,options={}){const l=layoutMatchTarget(options),p=l.panel,r=l.rail;c.save();backdrop(c,l.view,.9);rr(c,p,C.panel,C.line);const tx=l.wide?r.x+16:p.x+16,ty=p.y+28,tw=l.wide?r.w-32:p.w-32;label(c,options.title||'SELECT TARGET',tx,ty,{size:l.wide&&r.w<224?16:20,weight:800,fill:C.accent,width:tw});label(c,`${Math.max(0,finite(options.enemies))} ENEMIES IN ZONE`,tx,ty+28,{size:14,fill:options.enemies?'#ff8068':C.muted,width:tw});const legendY=l.wide?r.y+88:r.y+22;label(c,'◆ ENEMY',r.x+16,legendY,{fill:options.enemyColor||'#ff493f',size:14});label(c,!l.wide&&r.w<360?'▲ ALLY':'▲ FRIENDLY',r.x+16+(l.wide?0:(r.w-32)/3),legendY+(l.wide?24:0),{fill:options.friendColor||'#58b8ff',size:14});label(c,'▲ YOU',r.x+16+(l.wide?0:(r.w-32)*2/3),legendY+(l.wide?48:0),{size:14,width:l.wide?r.w-32:Math.max(0,(r.w-32)/3)});const hint=options.controller?(options.chosen?'TARGET LOCKED':'LEFT STICK TO AIM'):(options.chosen?'TARGET LOCKED':'TAP MAP TO AIM');label(c,hint,r.x+16,l.wide?Math.min(r.y+176,l.cancel.y-20):r.y+47,{size:14,fill:C.muted,width:r.w-32});button(c,l.cancel,options.controller?(options.chosen?'B  EDIT':'B  CANCEL'):'CANCEL',{active:options.focusId==='cancel'});button(c,l.confirm,options.controller?(options.chosen?'A  DEPLOY':'A  SELECT'):'DEPLOY',{primary:true,disabled:!options.chosen&&!options.controller,active:options.focusId==='confirm'});c.restore();return l;}

export function drawMatchNotice(c,options={}){const view=matchMenuViewport(options),lines=(options.lines||[]).filter(Boolean),p=centered(view,560,Math.min(320,104+lines.length*32));c.save();if(options.backdrop!==false)backdrop(c,view,.7);rr(c,p,C.panel,C.line);label(c,options.title||'MATCH',p.x+16,p.y+38,{size:options.large?36:24,weight:800,fill:options.accent||C.accent,width:p.w-32});lines.forEach((text,i)=>label(c,text,p.x+16,p.y+84+i*32,{size:16,fill:i===lines.length-1?C.muted:C.text,width:p.w-32}));c.restore();return{kind:'notice',view,panel:p,hits:[],focusTargets:[]};}
export function drawMatchReplay(c,options={}){const view=matchMenuViewport(options),p={x:view.x,y:view.y,w:view.w,h:108},skip=options.canSkip?{x:view.x+(view.w-Math.min(280,view.w))/2,y:view.y+view.h-60,w:Math.min(280,view.w),h:44}:null;c.save();rr(c,p,C.panel,C.line);label(c,options.title||'KILLCAM',p.x+16,p.y+26,{size:20,weight:800,fill:C.accent,width:p.w-32});label(c,options.players||'',p.x+16,p.y+55,{size:16,width:p.w-32});label(c,options.detail||'',p.x+16,p.y+84,{size:14,fill:C.muted,width:p.w-32});const bar={x:view.x,y:view.y+view.h-4,w:view.w,h:4};rr(c,bar,C.line);if(options.progress>0)rr(c,{...bar,w:bar.w*clamp(options.progress,0,1)},C.accent);if(skip)button(c,skip,options.controller?'A / B  SKIP REPLAY':'SKIP REPLAY');c.restore();return{kind:'replay',view,panel:p,skip,hits:skip?[hit('skip',skip,'skip')]:[],focusTargets:skip?[hit('skip',skip,'skip')]:[]};}

/** Normalized input ownership. All actions commit on release/accept and never mutate game state. */
export function createMatchMenuController(callbacks={}){
  let key='',layout=null,focusId='',press=null,epoch=0;
  const notifyFocus=()=>callbacks.onFocus?.(focusId,layout);
  const scrollTo=value=>{if(!layout?.body)return false;const next=clamp(value,0,layout.maxScroll);if(next===layout.scroll)return false;layout.scroll=next;callbacks.onScroll?.(next,layout);return true;};
  const ensureVisible=target=>{if(!target?.scrollItem||!layout?.body)return;const top=target.contentY,bottom=top+target.h;if(top<layout.scroll)scrollTo(top);else if(bottom>layout.scroll+layout.body.h)scrollTo(bottom-layout.body.h);};
  const focus=target=>{if(!target)return false;focusId=target.id;ensureVisible(target);notifyFocus();return true;};
  const targets=()=>layout?.focusTargets?.filter(t=>!t.disabled)||[];
  const activate=target=>{if(!target||target.disabled)return false;if(target.action==='page')return scrollTo(layout.scroll+target.direction*Math.max(layout.rowH||48,layout.body.h-(layout.rowH||48)));if(target.action==='back'){callbacks.onBack?.(layout);return true;}callbacks.onAction?.(target.action,target,layout);return true;};
  const move=direction=>{const all=targets();if(!all.length)return false;const current=all.find(t=>t.id===focusId);if(!current)return focus(all[0]);const dx=direction==='left'?-1:direction==='right'?1:0,dy=direction==='up'?-1:direction==='down'?1:0,cx=current.x+current.w/2,cy=current.y+current.h/2;let best=null,bestScore=Infinity;for(const t of all){if(t===current)continue;const x=t.x+t.w/2-cx,y=t.y+t.h/2-cy,along=x*dx+y*dy,cross=Math.abs(x*dy-y*dx);if(along<=1)continue;const score=along+cross*3;if(score<bestScore){bestScore=score;best=t;}}return focus(best);};
  const command=value=>{if(!layout)return false;if(value==='back'){callbacks.onBack?.(layout);return true;}if(value==='accept'){const all=targets();return activate(all.find(t=>t.id===focusId)||all[0]);}if(value==='previousTab'||value==='nextTab'){const direction=value==='previousTab'?-1:1;if(callbacks.onTab){callbacks.onTab(direction,layout);return true;}return scrollTo(layout.scroll+direction*(layout.body?.h||48));}if(value==='home')return focus(targets().find(t=>t.scrollItem)||targets()[0]);if(value==='end'){const list=targets().filter(t=>t.scrollItem);return focus(list[list.length-1]);}if(['up','down','left','right'].includes(value))return move(value);return false;};
  return{
    setLayout(nextKey,next){if(nextKey!==key){key=nextKey;epoch++;press=null;focusId='';}layout=next;if(layout&&!layout.focusTargets?.some(t=>t.id===focusId&&!t.disabled)){focusId=targets()[0]?.id||'';notifyFocus();}return layout;},
    getLayout:()=>layout,getHits:()=>layout?.hits||[],getFocus:()=>focusId,
    clear(){key='';layout=null;focusId='';press=null;epoch++;},
    focus(id){return focus(targets().find(t=>t.id===id));},command,
    key(code){const map={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',Enter:'accept',Space:'accept',Escape:'back',PageUp:'previousTab',PageDown:'nextTab',Home:'home',End:'end'};return command(map[code]||code);},
    gamepad(input={}){let handled=false;for(const [button,value] of [['B','back'],['A','accept'],['LB','previousTab'],['RB','nextTab'],['UP','up'],['DOWN','down'],['LEFT','left'],['RIGHT','right']])if(input[button]){handled=command(value)||handled;break;}if(Math.abs(finite(input.scrollY))>.12)handled=scrollTo((layout?.scroll||0)+input.scrollY*620*clamp(input.dt,.001,.1))||handled;return handled;},
    pointerDown({id=0,x,y,button=0}={}){if(!layout||press||button!==0)return false;const target=[...(layout.hits||[])].reverse().find(t=>matchMenuContains(t,x,y)),inside=matchMenuContains(layout.panel,x,y);if(!target&&!inside)return false;press={id,x,y,epoch,targetId:target?.id||'',scroll:layout.scroll||0,drag:false,scrollable:!!layout.maxScroll&&matchMenuContains(layout.body,x,y)};if(target&&!target.disabled)focus(target);return true;},
    pointerMove({id=0,x,y}={}){if(!press||id!==press.id)return false;if(press.scrollable&&Math.hypot(x-press.x,y-press.y)>8)press.drag=true;if(press.drag)scrollTo(press.scroll+press.y-y);return true;},
    pointerUp({id=0,x,y}={}){if(!press||id!==press.id)return false;const saved=press;press=null;if(saved.epoch!==epoch||saved.drag)return true;const target=layout?.hits?.find(t=>t.id===saved.targetId);if(target&&matchMenuContains(target,x,y))activate(target);return true;},
    pointerCancel(id){if(press&&(id==null||press.id===id)){press=null;return true;}return false;},
    wheel({x,y,deltaY}={}){if(!layout||!matchMenuContains(layout.panel,x,y))return false;scrollTo((layout.scroll||0)+finite(deltaY));return true;}
  };
}
