// One offscreen renderer, shared by the native armory and its thumbnail cache.
// Weapon geometry is borrowed from the live game; never dispose those resources.
import { equipmentModel, streakModel } from './menu-equipment.js?v=2.9.0';
export function createMenuScene({ready,weaponModel,partModel}) {
  let G,renderer,scene,camera,pivot,pending=false,failed=false;
  let current=null,key='',yaw=Math.PI/2+.20,pitch=-.10,zoom=1;
  const cache=new Map();
  function init(){if(renderer||pending||failed)return;pending=true;Promise.resolve(ready()).then(engine=>{if(!engine)throw Error('Preview unavailable');G=engine;renderer=new G.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(1);renderer.outputColorSpace=G.SRGBColorSpace;renderer.toneMapping=G.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;scene=new G.Scene();camera=new G.PerspectiveCamera(28,2,.01,40);scene.add(new G.HemisphereLight(0xf3f5df,0x33402e,2.8));for(const [color,intensity,pos] of [[0xffffff,2.3,[-3,4,4]],[0xc9e5d6,1.5,[4,1,-3]]]){const light=new G.DirectionalLight(color,intensity);light.position.set(...pos);scene.add(light);}pivot=new G.Group();scene.add(pivot);}).catch(()=>{failed=true;}).finally(()=>pending=false);}
  function make(kind,id,attachments,slot){return kind==='weapon'?weaponModel(id,attachments):kind==='part'?partModel(id,attachments,slot):kind==='streak'?streakModel(G,id):equipmentModel(G,id);}
  function disposeOwned(model){if(!model?.userData.menuOwned)return;model.traverse(n=>{n.geometry?.dispose();for(const m of Array.isArray(n.material)?n.material:[n.material])if(m){m.map?.dispose();m.dispose();}});}
  function cameraView(w,h){renderer.setSize(w,h,false);camera.aspect=w/h;camera.position.set(0,.05,3.6/zoom);camera.lookAt(0,0,0);camera.updateProjectionMatrix();pivot.rotation.set(pitch,yaw,0);scene.updateMatrixWorld(true);renderer.render(scene,camera);}
  function hero(kind,id,attachments={},w=600,h=290){init();if(!renderer)return {pending:!failed};const next=JSON.stringify([kind,id,attachments]);if(key!==next){disposeOwned(current);pivot.clear();current=make(kind,id,attachments);if(kind!=='weapon'){current.userData.menuOwned=true;const box=new G.Box3().setFromObject(current),size=box.getSize(new G.Vector3());current.position.sub(box.getCenter(new G.Vector3()));const wrapper=new G.Group();wrapper.add(current);wrapper.scale.setScalar(1.55/Math.max(size.x,size.y,size.z,.1));current=wrapper;current.userData.menuOwned=true;}pivot.add(current);if(!key||JSON.parse(key)[0]!==kind){yaw=kind==='weapon'?Math.PI/2+.20:.45;pitch=-.10;zoom=1;}key=next;}cameraView(w,h);const anchors={};for(const [slot,p]of Object.entries(current?.userData.calloutPoints||{})){const v=new G.Vector3(p.x,p.y,p.z);pivot.localToWorld(v);v.project(camera);anchors[slot]={x:(v.x*.5+.5)*w,y:(-v.y*.5+.5)*h};}return {canvas:renderer.domElement,anchors};}
  function thumb(kind,id,attachments={},slot=''){init();if(!renderer)return null;const k=JSON.stringify([kind,id,attachments,slot]);if(cache.has(k))return cache.get(k);const old=current,oldChildren=[...pivot.children],rotation=pivot.rotation.clone(),oldZoom=zoom;const model=make(kind,id,attachments,slot);if(!model)return null;pivot.clear();pivot.add(model);const box=new G.Box3().setFromObject(model),size=box.getSize(new G.Vector3()),center=box.getCenter(new G.Vector3());model.position.sub(center);const scale=2.0/Math.max(size.x,size.y,size.z,.01);model.scale.multiplyScalar(scale);model.position.multiplyScalar(scale);yaw=kind==='weapon'?Math.PI/2+.2:.55;pitch=-.15;zoom=kind==='part'?1.3:1;cameraView(240,120);const out=globalThis.document.createElement('canvas');out.width=240;out.height=120;out.getContext('2d').drawImage(renderer.domElement,0,0);cache.set(k,out);pivot.clear();pivot.add(...oldChildren);pivot.rotation.copy(rotation);yaw=rotation.y;pitch=rotation.x;zoom=oldZoom;current=old;if(kind==='equipment'||kind==='streak')model.userData.menuOwned=true;disposeOwned(model);return out;}
  return {hero,thumb,rotate(dx,dy){yaw+=dx*.012;pitch=Math.max(-1.1,Math.min(1.1,pitch+dy*.009));},zoom(delta){zoom=Math.max(.7,Math.min(1.65,zoom+delta));},reset(kind='weapon'){yaw=kind==='weapon'?Math.PI/2+.20:.45;pitch=-.10;zoom=1;},destroy(){disposeOwned(current);renderer?.dispose();cache.clear();}};
}
